DROP TABLE

IF EXISTS LOOKUP;
	CREATE TABLE LOOKUP (
		ID BIGINT (20) NOT NULL auto_increment
		,LOOKUP_TYPE VARCHAR(50) NOT NULL
		,LOOKUP_VALUE VARCHAR(200) NOT NULL
		,IS_ACTIVE CHAR(1) DEFAULT NULL
		,CREATED_ON DATETIME NOT NULL
		,CREATED_BY VARCHAR(50) NOT NULL
		,LAST_MOD_ON DATETIME NOT NULL
		,LAST_MOD_BY VARCHAR(50) NOT NULL
		,LOCK_TS SMALLINT (6) NOT NULL
		,PRIMARY KEY (ID)
		) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE

IF EXISTS LOGIN_USERS;
	CREATE TABLE LOGIN_USERS (
		ID BIGINT (20) NOT NULL auto_increment
		,USER_NAME VARCHAR(50) NOT NULL
		,FIRST_NAME VARCHAR(50) DEFAULT NULL
		,LAST_NAME VARCHAR(50) DEFAULT NULL
		,USER_ROLE BIGINT (20) NOT NULL
		,USER_DESCRIPTION VARCHAR(100) DEFAULT NULL
		,IS_ACTIVE CHAR(1) NOT NULL
		,GENDER BIGINT (20) NOT NULL
		,CREATED_ON DATETIME NOT NULL
		,CREATED_BY VARCHAR(50) NOT NULL
		,LAST_MOD_ON DATETIME NOT NULL
		,LAST_MOD_BY VARCHAR(50) NOT NULL
		,LOCK_TS BIGINT (20) NOT NULL
		,PRIMARY KEY (id)
		,UNIQUE KEY USER_NAME(USER_NAME)
		) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE

IF EXISTS USER_PASSWORD;
	CREATE TABLE USER_PASSWORD (
		ID BIGINT (20)
		,CURR_PASSWORD VARCHAR(100) DEFAULT NULL
		,RECENT_PASSWORD VARCHAR(100) DEFAULT NULL
		,LAST_PASSWORD VARCHAR(100) DEFAULT NULL
		,PASSWORD_ATTEMPTS INT (11) DEFAULT NULL
		,PASSWORD_EXPIRY_DATE DATETIME NOT NULL
		,IS_ACTIVE CHAR(1) DEFAULT '1'
		,IS_USER_LOCKED CHAR(1) DEFAULT '0'
		,CREATED_ON DATETIME
		,CREATED_BY VARCHAR(50) NOT NULL
		,LAST_MOD_ON DATETIME
		,LAST_MOD_BY VARCHAR(50) NOT NULL
		,LOCK_TS SMALLINT (6) DEFAULT 1
		,PRIMARY KEY (ID)
		,FOREIGN KEY (ID) REFERENCES LOGIN_USERS(ID) ON DELETE CASCADE
		) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP VIEW

IF EXISTS VIEW_USER_PASSWORD;
	CREATE VIEW VIEW_USER_PASSWORD
	AS
	SELECT LOGIN_USERS.ID
		,LOGIN_USERS.USER_NAME
		,LOGIN_USERS.FIRST_NAME
		,LOGIN_USERS.LAST_NAME
		,LOGIN_USERS.USER_ROLE
		,LOGIN_USERS.GENDER
		,LOGIN_USERS.IS_ACTIVE
		,USER_PASSWORD.CURR_PASSWORD
		,USER_PASSWORD.RECENT_PASSWORD
		,USER_PASSWORD.LAST_PASSWORD
		,USER_PASSWORD.PASSWORD_ATTEMPTS
		,USER_PASSWORD.PASSWORD_EXPIRY_DATE
		,USER_PASSWORD.IS_USER_LOCKED
	FROM USER_PASSWORD
	INNER JOIN LOGIN_USERS ON (USER_PASSWORD.ID = LOGIN_USERS.ID);

	DROP TABLE

	IF EXISTS LOGIN_HISTORY;
		CREATE TABLE LOGIN_HISTORY (
			ID BIGINT (20) NOT NULL auto_increment
			,USER_ID BIGINT (20) NOT NULL
			,IP_ADDRESS VARCHAR(50) NOT NULL
			,J_SESSION_ID VARCHAR(100) NOT NULL
			,CREATED_ON DATETIME NOT NULL
			,CREATED_BY VARCHAR(50) NOT NULL
			,LAST_MOD_ON DATETIME NOT NULL
			,LAST_MOD_BY VARCHAR(50) NOT NULL
			,LOCK_TS BIGINT (20) NOT NULL
			,IS_SUCCESS CHAR(1) DEFAULT NULL
			,SYSTEM_NAME VARCHAR(30) DEFAULT NULL
			,PRIMARY KEY (ID)
			) ENGINE = InnoDB DEFAULT CHARSET = utf8;

	DROP TABLE

	IF EXISTS AUDIT;
		CREATE TABLE AUDIT (
			ID BIGINT (20) NOT NULL AUTO_INCREMENT
			,OBJECT_NAME VARCHAR(255) NOT NULL
			,OBJECT_ID BIGINT
			,VALUE TEXT
			,CREATED_ON DATETIME NOT NULL
			,CREATED_BY VARCHAR(50) NOT NULL
			,LAST_MOD_ON DATETIME NOT NULL
			,LAST_MOD_BY VARCHAR(50) NOT NULL
			,LOCK_TS BIGINT (20) NOT NULL
			,PRIMARY KEY (ID)
			) ENGINE = INNODB DEFAULT CHARSET = utf8;
